az storage account updade \
	--resource-group main-testing \
	--name pedristorage \
	---access-tier Cool

az storage blob set-tier \
	--account-name pedristorage\
	--resource-group main-testing\
 	--name my_names\
	--tier Cool\
	--auth-mode login\